/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.transaction;

import com.amazon.spapi.model.orders.ErrorList;
import com.amazon.spapi.model.orders.OrderAddress;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * The response schema for the getOrderAddress operation.
 */
@ApiModel(description = "The response schema for the ListTransactionsResponse operation.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-03-10T10:27:36.694+08:00")
public class GetTransactionResponse {
  @SerializedName("payload")
  private ListTransactionsResponse payload = null;

  @SerializedName("statusCode")
  private Integer statusCode = null;

   /**
   * The payload for the getOrderAddress operations.
   * @return payload
  **/
  @ApiModelProperty(value = "The payload for the ListTransactionsResponse operations.")
  public ListTransactionsResponse getPayload() {
    return payload;
  }

   /**
   * One or more unexpected errors occurred during the getOrderAddress operation.
   * @return errors
  **/
  @ApiModelProperty(value = "One or more unexpected errors occurred during the getOrderAddress operation.")
  public Integer getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(Integer statusCode) {
    this.statusCode = statusCode;
  }



  @Override
  public int hashCode() {
    return Objects.hash(payload, statusCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTransactionResponse {\n");

    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    errors: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

