/*
 * The Selling Partner API for Finances
 * The Selling Partner API for Finances provides financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * OpenAPI spec version: 2024-06-19
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.transaction;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Information about the marketplace where the transaction occurred.
 */
@ApiModel(description = "Information about the marketplace where the transaction occurred.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-10-29T14:15:07.629+08:00")
public class MarketplaceDetails {
  @SerializedName("marketplaceId")
  private String marketplaceId = null;

  @SerializedName("marketplaceName")
  private String marketplaceName = null;

  public MarketplaceDetails marketplaceId(String marketplaceId) {
    this.marketplaceId = marketplaceId;
    return this;
  }

   /**
   * The identifier of the marketplace where the transaction occured.
   * @return marketplaceId
  **/
  @ApiModelProperty(value = "The identifier of the marketplace where the transaction occured.")
  public String getMarketplaceId() {
    return marketplaceId;
  }

  public void setMarketplaceId(String marketplaceId) {
    this.marketplaceId = marketplaceId;
  }

  public MarketplaceDetails marketplaceName(String marketplaceName) {
    this.marketplaceName = marketplaceName;
    return this;
  }

   /**
   * The name of the marketplace where the transaction occurred. For example: &#x60;Amazon.com&#x60;,&#x60;Amazon.in&#x60;
   * @return marketplaceName
  **/
  @ApiModelProperty(value = "The name of the marketplace where the transaction occurred. For example: `Amazon.com`,`Amazon.in`")
  public String getMarketplaceName() {
    return marketplaceName;
  }

  public void setMarketplaceName(String marketplaceName) {
    this.marketplaceName = marketplaceName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketplaceDetails marketplaceDetails = (MarketplaceDetails) o;
    return Objects.equals(this.marketplaceId, marketplaceDetails.marketplaceId) &&
        Objects.equals(this.marketplaceName, marketplaceDetails.marketplaceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(marketplaceId, marketplaceName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketplaceDetails {\n");

    sb.append("    marketplaceId: ").append(toIndentedString(marketplaceId)).append("\n");
    sb.append("    marketplaceName: ").append(toIndentedString(marketplaceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

