/*
 * The Selling Partner API for Finances
 * The Selling Partner API for Finances provides financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * OpenAPI spec version: 2024-06-19
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.transaction;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.Objects;

/**
 * Related business identifier of the transaction.
 */
@ApiModel(description = "Related business identifier of the transaction.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-10-29T14:15:07.629+08:00")
public class RelatedIdentifier {
  /**
   * An enumerated set of related business identifier names.
   */
  @JsonAdapter(RelatedIdentifierNameEnum.Adapter.class)
  public enum RelatedIdentifierNameEnum {
    ORDER_ID("ORDER_ID"),

    SHIPMENT_ID("SHIPMENT_ID"),

    FINANCIAL_EVENT_GROUP_ID("FINANCIAL_EVENT_GROUP_ID"),

    REFUND_ID("REFUND_ID"),

    INVOICE_ID("INVOICE_ID"),

    DISBURSEMENT_ID("DISBURSEMENT_ID"),

    TRANSFER_ID("TRANSFER_ID"),

    DEFERRED_TRANSACTION_ID("DEFERRED_TRANSACTION_ID");

    private String value;

    RelatedIdentifierNameEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RelatedIdentifierNameEnum fromValue(String text) {
      for (RelatedIdentifierNameEnum b : RelatedIdentifierNameEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<RelatedIdentifierNameEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RelatedIdentifierNameEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RelatedIdentifierNameEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return RelatedIdentifierNameEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("relatedIdentifierName")
  private RelatedIdentifierNameEnum relatedIdentifierName = null;

  @SerializedName("relatedIdentifierValue")
  private String relatedIdentifierValue = null;

  public RelatedIdentifier relatedIdentifierName(RelatedIdentifierNameEnum relatedIdentifierName) {
    this.relatedIdentifierName = relatedIdentifierName;
    return this;
  }

   /**
   * An enumerated set of related business identifier names.
   * @return relatedIdentifierName
  **/
  @ApiModelProperty(value = "An enumerated set of related business identifier names.")
  public RelatedIdentifierNameEnum getRelatedIdentifierName() {
    return relatedIdentifierName;
  }

  public void setRelatedIdentifierName(RelatedIdentifierNameEnum relatedIdentifierName) {
    this.relatedIdentifierName = relatedIdentifierName;
  }

  public RelatedIdentifier relatedIdentifierValue(String relatedIdentifierValue) {
    this.relatedIdentifierValue = relatedIdentifierValue;
    return this;
  }

   /**
   * Corresponding value of &#x60;RelatedIdentifierName&#x60;.
   * @return relatedIdentifierValue
  **/
  @ApiModelProperty(value = "Corresponding value of `RelatedIdentifierName`.")
  public String getRelatedIdentifierValue() {
    return relatedIdentifierValue;
  }

  public void setRelatedIdentifierValue(String relatedIdentifierValue) {
    this.relatedIdentifierValue = relatedIdentifierValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelatedIdentifier relatedIdentifier = (RelatedIdentifier) o;
    return Objects.equals(this.relatedIdentifierName, relatedIdentifier.relatedIdentifierName) &&
        Objects.equals(this.relatedIdentifierValue, relatedIdentifier.relatedIdentifierValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relatedIdentifierName, relatedIdentifierValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelatedIdentifier {\n");

    sb.append("    relatedIdentifierName: ").append(toIndentedString(relatedIdentifierName)).append("\n");
    sb.append("    relatedIdentifierValue: ").append(toIndentedString(relatedIdentifierValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

