/*
 * Selling Partner API for Listings Items
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide).
 *
 * OpenAPI spec version: 2021-08-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.listings;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.amazon.spapi.model.listings.Item;
import com.amazon.spapi.model.listings.Pagination;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Selling partner listings items and search related metadata.
 */
@ApiModel(description = "Selling partner listings items and search related metadata.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-12-19T17:08:06.914+08:00")
public class ItemSearchResults {
  @SerializedName("numberOfResults")
  private Integer numberOfResults = null;

  @SerializedName("pagination")
  private Pagination pagination = null;

  @SerializedName("items")
  private List<Item> items = new ArrayList<Item>();

  public ItemSearchResults numberOfResults(Integer numberOfResults) {
    this.numberOfResults = numberOfResults;
    return this;
  }

   /**
   * The total number of selling partner listings items found for the search criteria (only results up to the page count limit will be returned per request regardless of the number found).  Note: The maximum number of items (SKUs) that can be returned and paged through is 1000.
   * @return numberOfResults
  **/
  @ApiModelProperty(required = true, value = "The total number of selling partner listings items found for the search criteria (only results up to the page count limit will be returned per request regardless of the number found).  Note: The maximum number of items (SKUs) that can be returned and paged through is 1000.")
  public Integer getNumberOfResults() {
    return numberOfResults;
  }

  public void setNumberOfResults(Integer numberOfResults) {
    this.numberOfResults = numberOfResults;
  }

  public ItemSearchResults pagination(Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * If available, the &#x60;nextToken&#x60; and/or &#x60;previousToken&#x60; values required to return paginated results.
   * @return pagination
  **/
  @ApiModelProperty(value = "If available, the `nextToken` and/or `previousToken` values required to return paginated results.")
  public Pagination getPagination() {
    return pagination;
  }

  public void setPagination(Pagination pagination) {
    this.pagination = pagination;
  }

  public ItemSearchResults items(List<Item> items) {
    this.items = items;
    return this;
  }

  public ItemSearchResults addItemsItem(Item itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * A list of listings items.
   * @return items
  **/
  @ApiModelProperty(required = true, value = "A list of listings items.")
  public List<Item> getItems() {
    return items;
  }

  public void setItems(List<Item> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemSearchResults itemSearchResults = (ItemSearchResults) o;
    return Objects.equals(this.numberOfResults, itemSearchResults.numberOfResults) &&
        Objects.equals(this.pagination, itemSearchResults.pagination) &&
        Objects.equals(this.items, itemSearchResults.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfResults, pagination, items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemSearchResults {\n");

    sb.append("    numberOfResults: ").append(toIndentedString(numberOfResults)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

