/*
 * Selling Partner API for Retail Procurement Orders
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.vendororders;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Ordered quantity information.
 */
@ApiModel(description = "Ordered quantity information.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-07-02T11:17:12.944+08:00")
public class OrderItemStatusOrderedQuantity {
  @SerializedName("orderedQuantity")
  private ItemQuantity orderedQuantity = null;

  @SerializedName("orderedQuantityDetails")
  private List<OrderedQuantityDetails> orderedQuantityDetails = null;

  public OrderItemStatusOrderedQuantity orderedQuantity(ItemQuantity orderedQuantity) {
    this.orderedQuantity = orderedQuantity;
    return this;
  }

   /**
   * Item quantity ordered.
   * @return orderedQuantity
  **/
  @ApiModelProperty(value = "Item quantity ordered.")
  public ItemQuantity getOrderedQuantity() {
    return orderedQuantity;
  }

  public void setOrderedQuantity(ItemQuantity orderedQuantity) {
    this.orderedQuantity = orderedQuantity;
  }

  public OrderItemStatusOrderedQuantity orderedQuantityDetails(List<OrderedQuantityDetails> orderedQuantityDetails) {
    this.orderedQuantityDetails = orderedQuantityDetails;
    return this;
  }

  public OrderItemStatusOrderedQuantity addOrderedQuantityDetailsItem(OrderedQuantityDetails orderedQuantityDetailsItem) {
    if (this.orderedQuantityDetails == null) {
      this.orderedQuantityDetails = new ArrayList<OrderedQuantityDetails>();
    }
    this.orderedQuantityDetails.add(orderedQuantityDetailsItem);
    return this;
  }

   /**
   * Details of item quantity ordered.
   * @return orderedQuantityDetails
  **/
  @ApiModelProperty(value = "Details of item quantity ordered.")
  public List<OrderedQuantityDetails> getOrderedQuantityDetails() {
    return orderedQuantityDetails;
  }

  public void setOrderedQuantityDetails(List<OrderedQuantityDetails> orderedQuantityDetails) {
    this.orderedQuantityDetails = orderedQuantityDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderItemStatusOrderedQuantity orderItemStatusOrderedQuantity = (OrderItemStatusOrderedQuantity) o;
    return Objects.equals(this.orderedQuantity, orderItemStatusOrderedQuantity.orderedQuantity) &&
        Objects.equals(this.orderedQuantityDetails, orderItemStatusOrderedQuantity.orderedQuantityDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderedQuantity, orderedQuantityDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderItemStatusOrderedQuantity {\n");
    
    sb.append("    orderedQuantity: ").append(toIndentedString(orderedQuantity)).append("\n");
    sb.append("    orderedQuantityDetails: ").append(toIndentedString(orderedQuantityDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

