/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.awd;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * Represents a distribution package with its respective quantity.
 */
@ApiModel(description = "Represents a distribution package with its respective quantity.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-12-13T16:08:01.615+08:00")
public class DistributionPackageQuantity {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("distributionPackage")
  private DistributionPackage distributionPackage = null;

  public DistributionPackageQuantity count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Number of cases or pallets with the same package configuration.
   * @return count
  **/
  @ApiModelProperty(required = true, value = "Number of cases or pallets with the same package configuration.")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public DistributionPackageQuantity distributionPackage(DistributionPackage distributionPackage) {
    this.distributionPackage = distributionPackage;
    return this;
  }

   /**
   * Get distributionPackage
   * @return distributionPackage
  **/
  @ApiModelProperty(required = true, value = "")
  public DistributionPackage getDistributionPackage() {
    return distributionPackage;
  }

  public void setDistributionPackage(DistributionPackage distributionPackage) {
    this.distributionPackage = distributionPackage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DistributionPackageQuantity distributionPackageQuantity = (DistributionPackageQuantity) o;
    return Objects.equals(this.count, distributionPackageQuantity.count) &&
        Objects.equals(this.distributionPackage, distributionPackageQuantity.distributionPackage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, distributionPackage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DistributionPackageQuantity {\n");

    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    distributionPackage: ").append(toIndentedString(distributionPackage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

