/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.awd;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents a product with the SKU details and the corresponding quantity.
 */
@ApiModel(description = "Represents a product with the SKU details and the corresponding quantity.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-12-13T16:08:01.615+08:00")
public class ProductQuantity {
  @SerializedName("attributes")
  private List<ProductAttribute> attributes = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("sku")
  private String sku = null;

  public ProductQuantity attributes(List<ProductAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public ProductQuantity addAttributesItem(ProductAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<ProductAttribute>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Attributes for this instance of the product. For example, already-prepped, or other attributes that distinguish the product beyond the SKU.
   * @return attributes
  **/
  @ApiModelProperty(value = "Attributes for this instance of the product. For example, already-prepped, or other attributes that distinguish the product beyond the SKU.")
  public List<ProductAttribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<ProductAttribute> attributes) {
    this.attributes = attributes;
  }

  public ProductQuantity quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Product quantity.
   * @return quantity
  **/
  @ApiModelProperty(required = true, value = "Product quantity.")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public ProductQuantity sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * The seller or merchant SKU.
   * @return sku
  **/
  @ApiModelProperty(required = true, value = "The seller or merchant SKU.")
  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductQuantity productQuantity = (ProductQuantity) o;
    return Objects.equals(this.attributes, productQuantity.attributes) &&
        Objects.equals(this.quantity, productQuantity.quantity) &&
        Objects.equals(this.sku, productQuantity.sku);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, quantity, sku);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductQuantity {\n");

    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

