/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.awd;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Sort order for a collection of items. For example, order or shipment.
 */
@JsonAdapter(SortOrder.Adapter.class)
public enum SortOrder {

  ASCENDING("ASCENDING"),

  DESCENDING("DESCENDING");

  private String value;

  SortOrder(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SortOrder fromValue(String text) {
    for (SortOrder b : SortOrder.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SortOrder> {
    @Override
    public void write(final JsonWriter jsonWriter, final SortOrder enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SortOrder read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SortOrder.fromValue(String.valueOf(value));
    }
  }
}

