/*
 * Selling Partner API for FBA Inbound Eligibilty
 * With the FBA Inbound Eligibility API, you can build applications that let sellers get eligibility previews for items before shipping them to Amazon's fulfillment centers. With this API you can find out if an item is eligible for inbound shipment to Amazon's fulfillment centers in a specific marketplace. You can also find out if an item is eligible for using the manufacturer barcode for FBA inventory tracking. Sellers can use this information to inform their decisions about which items to ship Amazon's fulfillment centers.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.api;

import com.amazon.spapi.client.ApiException;
import com.amazon.spapi.config.AmazonAuthorConfig;
import com.amazon.spapi.model.fbainboundeligibility.GetItemEligibilityPreviewResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.*;

/**
 * API tests for FbaInboundApi
 */
@Ignore
public class FbaInboundEligibilityApiTest {
    static String refreshtoken="***";
    List<String> marketplaceIds = Arrays.asList("ATVPDKIKX0DER");
    AmazonAuthorConfig authorConfig=new AmazonAuthorConfig(refreshtoken, "us-east-1","https://sellingpartnerapi-na.amazon.com");

    private final FbaInboundEligibilityApi api = FbaInboundEligibilityApi.amazonAuthorizationApi(authorConfig);


    /**
     *
     *
     * This operation gets an eligibility preview for an item that you specify. You can specify the type of eligibility preview that you want (INBOUND or COMMINGLING). For INBOUND previews, you can specify the marketplace in which you want to determine the item&#39;s eligibility.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getItemEligibilityPreviewTest() throws ApiException {
        String asin = "DGDFGG";
        String program = "INBOUND";
        List<String> marketplaceIds = this.marketplaceIds;
        GetItemEligibilityPreviewResponse response = api.getItemEligibilityPreview(asin, program, marketplaceIds);
        System.out.println(response);
        // TODO: test validations
    }

}
