/*
 * Selling Partner API for Listings Items
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2021-08-01.md).
 *
 * OpenAPI spec version: 2021-08-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.api;

import cn.hutool.json.JSONUtil;
import com.amazon.spapi.config.AmazonAuthorConfig;
import com.amazon.spapi.enums.EndpointsEnum;
import com.amazon.spapi.enums.ReportTypeEnum;
import org.junit.Test;
import org.junit.Ignore;

import com.amazon.spapi.client.*;
import com.amazon.spapi.model.listings.*;

import java.util.*;

/**
 * API tests for ListingsApi
 */
@Ignore
public class ListingsApiTest {


    static String refreshtoken="***";
    static EndpointsEnum endpointsEnum = EndpointsEnum.US;
    static List<String> marketplaceIds= Arrays.asList(endpointsEnum.getMarketplaceId());
    AmazonAuthorConfig authorConfig=new AmazonAuthorConfig(refreshtoken, endpointsEnum.getRegion(),endpointsEnum.getEndpoint());

    private final ListingsApi api =  ListingsApi.amazonAuthorizationApi(authorConfig);;

    static  String sku="YYYYYnZBT-fn-skblu";
    /**
     *
     *
     * Delete a listings item for a selling partner.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteListingsItemTest() throws ApiException {
        String sellerId = null;
        String sku = null;
        List<String> marketplaceIds = null;
        String issueLocale = null;
        ListingsItemSubmissionResponse response = api.deleteListingsItem(sellerId, sku, marketplaceIds, issueLocale);

        // TODO: test validations
    }

    /**
     *
     *
     * Returns details about a listings item for a selling partner.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getListingsItemTest() throws ApiException {
        String sellerId ="YYYYYY";
        String sku ="YYYYYYYYF-YGgrn-fA";
        List<String> marketplaceIds = this.marketplaceIds;
        String issueLocale = null;
        List<String> includedData = Arrays.asList("attributes");
        Item response = api.getListingsItem(sellerId, sku, marketplaceIds, issueLocale, includedData);
      //  System.out.println(response);

        String t1=JSONUtil.toJsonStr(response.getAttributes());
        System.out.println(t1);

        // TODO: test validations
    }

    /**
     *
     *
     * Partially update (patch) a listings item for a selling partner. Only top-level listings item attributes can be patched. Patching nested attributes is not supported.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchListingsItemTest() throws ApiException {
        String sellerId = null;
        String sku = null;
        List<String> marketplaceIds = null;
        ListingsItemPatchRequest body = null;
        String issueLocale = null;
        ListingsItemSubmissionResponse response = api.patchListingsItem(sellerId, sku, marketplaceIds, body, issueLocale);

        // TODO: test validations
    }

    /**
     *
     *
     * Creates a new or fully-updates an existing listings item for a selling partner.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/usage-plans-rate-limits/Usage-Plans-and-Rate-Limits.md).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putListingsItemTest() throws ApiException {
        String sellerId = "A2QT1VJWM8ZW05";
        String sku = "JYCX-TM-D6-KD35-PWht-dychz-Supoman";
        List<String> marketplaceIds = this.marketplaceIds;
        ListingsItemPutRequest body = new ListingsItemPutRequest();
        body.setProductType("CONSUMER_ELECTRONICS");
        body.setRequirements(ListingsItemPutRequest.RequirementsEnum.LISTING);
        body.setAttributes("{\n" +
                "    \"productType\":\"CAR_ALARM\",\n" +
                "    \"requirements\":\"LISTING\",\n" +
                "    \"attributes\":{\n" +
                "\t\t \"externally_assigned_product_identifier\":[\n" +
                "            {\n" +
                "                \"value\":\"840034600957\",\n" +
                "                \"type\":\"upc\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"condition_type\":[\n" +
                "            {\n" +
                "                \"value\":\"new_new\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"item_type_keyword\":[\n" +
                "            {\n" +
                "                \"value\":\"safe-accessories\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"product_description\":[\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"<b>Upgraded Liquid Silicone Fiberglass Cloth Anti-corrosion Fireproof Water Resistant Signal Blocking Clutch Bag</b><br><br> <b>Material:</b><br><br> The outer layer is made of an upgraded liquid silicone fiberglass cloth with low thermal conductivity and strong fire resistance. So the clutch bag can withstand temperatures up to 1000°C (About 1832°F). And the inner layer is an electromagnetic shielding cloth, which can stop the signal and protect your personal information. So you can keep all your valuables 100% safe.<br><br> <b>Good Protection:</b><br><br> Effectively prevent water vapor penetration, which will ensure a safe environment for your valuables.<br><br> <b>Large Space:</b><br><br> There is a zipper pocket and a multiple-functional bag to store your valuables. You can place notes, jewelry, checks, cash, passports, licenses, USB sticks, coins, precious photos, etc. You can store the bag in your safe, drawer, cabinet, or even your car. It is convenient for using at home or in the office.<br><br> <b>Zipper and HOOK & LOOP Closure for Double Protection:</b><br><br> This fireproof signal stopping clutch bag features with a zipper and HOOK & LOOP closure design, provides you with double security and maximum protection.<br><br> <b>Dimension: 8.26 x 4.52 inch (21cm x 11.5cm)</b><br><br> <b>Weight: 2.88 OZ</b><br><br> <b>Package Included:</b><br><br> 1 x Fireproof Signal Blocking Bag<br><br>\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"item_name\":[\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"Fireproof Signal Blocking Bag, GPS RFID Faraday Bag Shield Cage Pouch Wallet Protective Case for Privacy Protection and Car Key FOB - Black\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"bullet_point\":[\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"PREMIUM MATERIAL: The outer layer is made of an upgraded liquid silicone fiberglass cloth with low thermal conductivity and strong fire resistance. So the clutch bag can withstand temperatures up to 1000°C (About 1832°F). At the same time, the surface of the liquid silicone fiberglass cloth layer is smooth and comfortable, which will not cause skin irritation or discomfort.\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"FIREPROOF ZIPPER: The fire resistant zipper can withstand temperatures up to 300°C. And the HOOK & LOOP design adds more convenience. Provides your valuables with a maximum protection.\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"SINGNAL BLOCKING: The inside layer of the zipper clutch bag is made of an electromagnetic shielding cloth, which can stop the signal and protect your personal information. It can block external calls without switching off the cell phone.\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"LARGE CAPACITY: The slim lightweight portable clutch bag has a large capacity. There is a zipper pocket and a multiple-functional bag to store your valuables. You can place notes, jewelry, checks, cash, passports, licenses, USB sticks, coins, precious photos, etc. You can store the bag in your safe, drawer, cabinet, or even your car. It is convenient for using at home or in the office.\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"WATER RESISTANT: The fireproof signal blocking bag with water resistant function, which keeps your valuables and information safe always.\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"color\":[\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"Black\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"item_package_dimensions\":[\n" +
                "            {\n" +
                "                \"height\":{\n" +
                "                    \"unit\":\"inches\",\n" +
                "                    \"value\":\"0.60\"\n" +
                "                },\n" +
                "                \"length\":{\n" +
                "                    \"unit\":\"inches\",\n" +
                "                    \"value\":\"8.86\"\n" +
                "                },\n" +
                "                \"width\":{\n" +
                "                    \"unit\":\"inches\",\n" +
                "                    \"value\":\"5.90\"\n" +
                "                },\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"item_package_weight\":[\n" +
                "            {\n" +
                "                \"unit\":\"ounces\",\n" +
                "                \"value\":\"2.95\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"purchasable_offer\":[\n" +
                "            {\n" +
                "                \"currency\":\"USD\",\n" +
                "                \"our_price\":[\n" +
                "                    {\n" +
                "                        \"schedule\":[\n" +
                "                            {\n" +
                "                                \"value_with_tax\":13.99\n" +
                "                            }\n" +
                "                        ]\n" +
                "                    }\n" +
                "                ],\n" +
                "                \"discounted_price\":[\n" +
                "                    {\n" +
                "                        \"schedule\":[\n" +
                "                            {\n" +
                "                                \"end_at\":\"2022-08-31T05:00:00.000Z\",\n" +
                "                                \"start_at\":\"2022-08-17T05:00:00.000Z\",\n" +
                "                                \"value_with_tax\":8.95\n" +
                "                            }\n" +
                "                        ]\n" +
                "                    }\n" +
                "                ],\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"manufacturer\":[\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"J&D Tech\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"brand\":[\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"J&D\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"number_of_items\":[\n" +
                "            {\n" +
                "                \"value\":25,\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"number_of_boxes\":[\n" +
                "            {\n" +
                "                \"value\":1,\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"included_components\":[\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"QLED Standard Smart Remote\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"Power Cable\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"Stand\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"Samsung Smart Control\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"warranty_description\":[\n" +
                "            {\n" +
                "                \"language_tag\":\"en_US\",\n" +
                "                \"value\":\"1 year manufacturer\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"cpsia_cautionary_statement\":[\n" +
                "            {\n" +
                "                \"value\":\"no_warning_applicable\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"supplier_declared_dg_hz_regulation\":[\n" +
                "            {\n" +
                "                \"value\":\"not_applicable\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "       \n" +
                "        \"batteries_required\":[\n" +
                "            {\n" +
                "                \"value\":\"false\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"country_of_origin\":[\n" +
                "            {\n" +
                "                \"value\":\"CN\",\n" +
                "                \"marketplace_id\":\"ATVPDKIKX0DER\"\n" +
                "            }\n" +
                "        ]\n" +
                "    }\n" +
                "}");
        String issueLocale = null;
        ListingsItemSubmissionResponse response = api.putListingsItem(sellerId, sku, marketplaceIds, body, issueLocale);
        System.out.println(response);
        // TODO: test validations

        // Create a PutListingsItemRequest

    }

}
