/*
 * Selling Partner API for Sales
 * The Selling Partner API for Sales provides APIs related to sales performance.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.api;

import com.amazon.spapi.client.ApiException;
import com.amazon.spapi.config.AmazonAuthorConfig;
import com.amazon.spapi.enums.EndpointsEnum;
import com.amazon.spapi.model.sales.GetOrderMetricsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.*;

/**
 * API tests for SalesApi
 */
@Ignore
public class SalesApiTest {


    static String refreshtoken="***";
    static EndpointsEnum endpointsEnum = EndpointsEnum.US;
    static List<String> marketplaceIds= Arrays.asList(endpointsEnum.getMarketplaceId());
    static  AmazonAuthorConfig authorConfig=new AmazonAuthorConfig(refreshtoken, endpointsEnum.getRegion(),endpointsEnum.getEndpoint());
    private final SalesApi api =  SalesApi.amazonAuthorizationApi(authorConfig);;

    /**
     *
     *
     * Returns aggregated order metrics for given interval, broken down by granularity, for given buyer type.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | .5 | 15 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrderMetricsTest() throws ApiException {
        List<String> marketplaceIds = Arrays.asList(endpointsEnum.getMarketplaceId());
        String interval = null;
        String granularity = "Day";
        String granularityTimeZone = null;
        String buyerType = null;
        String fulfillmentNetwork = null;
        String firstDayOfWeek = null;
        String asin = null;
        String sku = null;
        GetOrderMetricsResponse response = api.getOrderMetrics(marketplaceIds, interval, granularity, granularityTimeZone, buyerType, fulfillmentNetwork, firstDayOfWeek, asin, sku);
        System.out.println(response);
        // TODO: test validations
    }

}
